- name: apt get update
  apt: update_cache=yes

- name: install useful stuff
  action: apt pkg={{item}} state=installed
  with_items:
    - ntp
    - vim
    - openjdk-8-jdk-headless
    - ruby
    - ruby-dev
    - ruby-all-dev
    - ruby-bundler
    - postgresql
    - libpq-dev
    - pkg-config
    - ruby-pkg-config
    - libmagickwand-dev
    - imagemagick
    - libssl-dev
    - libffi-dev
    - dstat
    - htop
    - direnv
    - python-psycopg2
    - awscli
    - jq

