- hosts: box
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    - common
    - aws
    - developer
    - geerlingguy.nodejs
  environment:
    AWS_ACCESS_KEY_ID: INSERT-YOUR-KEY
    AWS_SECRET_KEY: INSERT-YOUR-SECRET-KEY
